param([switch]$SelfTest)
# Kevin Skill Lab v1.0.5 - preserve learned-skill registry on corrupt/missing evidence.
# Authority delta: NONE. Primitive allowlist unchanged. No arbitrary shell/code.
$ErrorActionPreference='Stop';$u=New-Object Text.UTF8Encoding($false);$ws=$PSScriptRoot
$a=Join-Path $ws 'reports\action-era';$sr=Join-Path $a 'skills';$rr=Join-Path $sr 'ready';$run=Join-Path $sr 'running';$sd=Join-Path $sr 'done';$sf=Join-Path $sr 'failed'
$reg=Join-Path $ws 'reports\capabilities\composite-skills.json';$qr=Join-Path $a 'queue\ready';$qrun=Join-Path $a 'queue\running';$qd=Join-Path $a 'queue\done';$qf=Join-Path $a 'queue\failed';$staleMin=15;$maxRecover=3
$LeaseBridge=Join-Path $ws 'ControlPlane\Invoke-KevinMissionLease.ps1'
$LeaseStore=Join-Path $ws 'reports\autonomy-runtime\mission-leases-v1.json'
$LeaseHolder='skill-lab'
foreach($d in @($rr,$run,$sd,$sf,(Split-Path $reg -Parent),$qr,$qrun,$qd,$qf)){New-Item -ItemType Directory -Force $d|Out-Null}

function Invoke-MissionLease([string]$LeaseAction,[string]$MissionId='', [string]$EvidenceUri='', [string]$Reason='COMPLETE'){if(-not(Test-Path -LiteralPath $LeaseBridge -PathType Leaf)){return $null};try{$a=@('-NoProfile','-File',$LeaseBridge,'-Action',$LeaseAction,'-StorePath',$LeaseStore,'-Holder',$LeaseHolder);if($MissionId){$a+=@('-MissionId',$MissionId)};if($EvidenceUri){$a+=@('-EvidenceUri',$EvidenceUri)};if($LeaseAction-eq'Release'){$a+=@('-Reason',$Reason)};return ((& powershell @a 2>&1)|Out-String).Trim()}catch{return $null}}
function W([string]$p,[object]$o){$t=$p+'.tmp-'+$PID+'-'+[guid]::NewGuid().ToString('N');[IO.File]::WriteAllText($t,($o|ConvertTo-Json -Depth 50),$u);Move-Item $t $p -Force}
function ReadJ([string]$p){if(-not(Test-Path $p -PathType Leaf)){return $null};try{Get-Content $p -Raw|ConvertFrom-Json}catch{return $null}}
function HT([string]$x){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($x))).Replace('-',''))}finally{$h.Dispose()}}
function C([object]$v){if($null-eq$v){return $null};if($v-is[string]-or$v-is[ValueType]){return $v};if($v-is[Collections.IDictionary]){$o=[ordered]@{};foreach($k in @($v.Keys|%{[string]$_}|sort)){$o[$k]=C $v[$k]};return $o};if($v-is[Collections.IEnumerable]-and-not($v-is[string])){$z=@();foreach($x in $v){$z+=,(C $x)};return $z};$o=[ordered]@{};foreach($k in @($v.PSObject.Properties|?{$_.MemberType -in @('NoteProperty','Property')}|% Name|sort)){$o[$k]=C $v.$k};$o}
function HO([object]$v){HT ((C $v)|ConvertTo-Json -Depth 50 -Compress)}
function Note($o,[string]$n,$v){if(-not($o.PSObject.Properties.Name-contains$n)){$o|Add-Member NoteProperty $n $v}}
function SafeName([string]$n,[string[]]$e){if([string]::IsNullOrWhiteSpace($n)-or$n.Length-gt96-or$n-match'[\\/:*?"<>|]'-or$n.Contains('..')){throw'filename invalid'};if(-not($e-contains[IO.Path]::GetExtension($n).ToLowerInvariant())){throw'file extension not allowlisted'}}
function Workbook($x){if(-not$x-or[int]$x.schema-ne1-or[string]$x.kind-ne'kevin-xlsx-spec'){throw'workbook invalid'};$ss=@($x.sheets);if($ss.Count-lt1-or$ss.Count-gt5){throw'workbook sheets invalid'};$ch=0;foreach($s in $ss){if([string]::IsNullOrWhiteSpace([string]$s.name)-or([string]$s.name).Length-gt31-or[string]$s.name-match'[\\/*?:\[\]]'){throw'sheet name invalid'};$rows=@($s.rows);if($rows.Count-gt200){throw'row cap'};foreach($r in $rows){$cells=@($r);if($cells.Count-gt16){throw'column cap'};foreach($c in $cells){$ch+=([string]$c).Length}}};if($ch-gt120000){throw'workbook content cap'}}
function Step($s){if(-not$s){throw'step missing'};$op=[string]$s.operation;if(-not(@('create_text','create_spreadsheet','ui_notepad_write')-contains$op)){throw'step primitive not proven/allowlisted'};if(-not$s.payload){throw'payload missing'};if($op-eq'create_text'){SafeName ([string]$s.payload.filename) @('.md','.txt');if(([string]$s.payload.content).Length-gt60000){throw'text cap'}}elseif($op-eq'create_spreadsheet'){SafeName ([string]$s.payload.filename) @('.xlsx');Workbook $s.payload.workbook}else{SafeName ([string]$s.payload.filename) @('.txt');$c=[string]$s.payload.content;if([string]::IsNullOrWhiteSpace($c)-or$c.Length-gt12000-or$c.IndexOf([char]0)-ge0){throw'ui text invalid'};if($s.payload.PSObject.Properties.Name-contains'app'){if([string]$s.payload.app-ne'notepad'){throw'ui app not allowlisted'}}}}
function Skill($x){if(-not$x-or[int]$x.schema-ne1-or[string]$x.kind-ne'kevin-composite-skill'-or[string]$x.authority-ne'GREEN'){throw'skill schema/authority invalid'};if([string]$x.id-notmatch'^[A-Za-z0-9._-]{4,80}$'-or[string]$x.version-notmatch'^[A-Za-z0-9._-]{1,32}$'){throw'skill identity invalid'};if($x.name-isnot[string]-or[string]::IsNullOrWhiteSpace($x.name)-or$x.name.Length-gt120){throw'skill name invalid'};$ss=@($x.steps);if($ss.Count-lt1-or$ss.Count-gt12){throw'step count invalid'};foreach($s in $ss){Step $s}}
function D($st,[int]$i){$s=@($st.manifest.steps)[$i];Step $s;$id='skill-'+[string]$st.manifest.id+'-'+[string]$st.manifest.version+'-s'+('{0:D2}'-f($i+1));[pscustomobject]@{id=$id;key='skill:'+[string]$st.manifest.id+':'+[string]$st.manifest.version+':step:'+($i+1);op=[string]$s.operation;payload=$s.payload;ph=HO $s.payload}}
function Order($st,[int]$i){$d=D $st $i;[ordered]@{schema=1;kind='kevin-green-work-order';id=$d.id;semantic_key=$d.key;authority='GREEN';operation=$d.op;payload=$d.payload}}
function Match($o,$d){$o-and[int]$o.schema-eq1-and[string]$o.kind-eq'kevin-green-work-order'-and[string]$o.id-eq$d.id-and[string]$o.semantic_key-eq$d.key-and[string]$o.authority-eq'GREEN'-and[string]$o.operation-eq$d.op-and(HO $o.payload)-eq$d.ph}
function Find([string]$id){$h=@();foreach($x in @(@('READY',$qr),@('RUNNING',$qrun),@('DONE',$qd),@('FAILED',$qf))){$p=Join-Path $x[1] ($id+'.json');if(Test-Path $p -PathType Leaf){$h+=,[pscustomobject]@{state=$x[0];path=$p;order=ReadJ $p}}};if($h.Count-gt1){throw'duplicate work-order records'};if($h.Count){$h[0]}else{$null}}
function Age([string]$x){if([string]::IsNullOrWhiteSpace($x)){return[double]::PositiveInfinity};try{([DateTimeOffset]::Now-[DateTimeOffset]::Parse($x)).TotalMinutes}catch{return[double]::PositiveInfinity}}
function Init($s){Note $s 'recovery_attempts' 0;Note $s 'last_transition_at' ([string]$s.started_at);Note $s 'runner_heartbeat_at' '';Note $s 'last_recovery_reason' '';Note $s 'current_order_state' '';Note $s 'current_step_payload_sha256' '';Note $s 'current_semantic_key' '';Note $s 'failure_evidence_sha256' '';Note $s 'step_started_at' ''}
function SaveT([string]$p,$s,[string]$why){$s.last_transition_at=(Get-Date).ToString('o');$s.runner_heartbeat_at=$s.last_transition_at;$s.last_recovery_reason=$why;W $p $s;if($s.manifest){[void](Invoke-MissionLease 'Heartbeat' ([string]$s.manifest.id) ('reports/action-era/skills/running/'+[IO.Path]::GetFileName($p)))}}
function MoveR([string]$p,[string]$d){$z=Join-Path $d ([IO.Path]::GetFileName($p));Move-Item $p $z -Force;$z}
function RegistryTimestampValid($value) {
    # ConvertFrom-Json preserves ISO timestamps as strings in Windows PowerShell
    # and may materialize DateTime values in PowerShell 7. Accept both without
    # coercing numeric/boolean evidence into a timestamp or rewriting the file.
    if($value-is[DateTime]-or$value-is[DateTimeOffset]){return $true}
    if($value-isnot[string]-or$value.Length-gt40){return $false}
    $stamp=[DateTimeOffset]::MinValue
    return [DateTimeOffset]::TryParse($value,[ref]$stamp)
}
function Assert-RegistryValid($x) {
    if($null-eq$x-or$x-is[array]-or$x-is[string]-or$x-is[ValueType]){throw 'SKILL_REGISTRY_INVALID_ROOT'}
    if(($x.schema-isnot[int]-and$x.schema-isnot[long])-or[int]$x.schema-ne1-or[string]$x.kind-ne'kevin-composite-skill-registry'){throw 'SKILL_REGISTRY_INVALID_SCHEMA'}
    if($x.skills-isnot[array]-or@($x.skills).Count-gt2048){throw 'SKILL_REGISTRY_INVALID_SKILLS'}
    if(-not(RegistryTimestampValid $x.updated_at)){throw 'SKILL_REGISTRY_INVALID_TIMESTAMP'}
    $seen=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
    foreach($entry in @($x.skills)){
        if($null-eq$entry-or$entry-is[string]-or$entry-is[ValueType]-or$entry-is[array]){throw 'SKILL_REGISTRY_INVALID_ENTRY'}
        foreach($field in @('id','version','key','authority','status','name','manifest_sha256','proof_sha256','result_file')){if($entry.$field-isnot[string]){throw 'SKILL_REGISTRY_INVALID_FIELD_TYPE'}}
        if([string]$entry.id-notmatch'^[A-Za-z0-9._-]{4,80}$'-or[string]$entry.version-notmatch'^[A-Za-z0-9._-]{1,32}$'){throw 'SKILL_REGISTRY_INVALID_IDENTITY'}
        if([string]$entry.key-cne([string]$entry.id+'@'+[string]$entry.version)-or-not$seen.Add([string]$entry.key)){throw 'SKILL_REGISTRY_DUPLICATE_OR_MISMATCHED_KEY'}
        if([string]$entry.authority-cne'GREEN'-or[string]$entry.status-cne'PROVEN'){throw 'SKILL_REGISTRY_UNPROVEN_OR_UNAUTHORIZED_ENTRY'}
        if([string]::IsNullOrWhiteSpace([string]$entry.name)-or([string]$entry.name).Length-gt120){throw 'SKILL_REGISTRY_INVALID_NAME'}
        foreach($field in @('manifest_sha256','proof_sha256')){if([string]$entry.$field-notmatch'^[A-Fa-f0-9]{64}$'){throw 'SKILL_REGISTRY_INVALID_PROOF_HASH'}}
        if(-not(RegistryTimestampValid $entry.proven_at)){throw 'SKILL_REGISTRY_INVALID_PROOF_TIMESTAMP'}
        $file=[string]$entry.result_file
        if($file.Length-gt160-or$file-notmatch'^[A-Za-z0-9._-]+\.json$'-or$file.Contains('..')){throw 'SKILL_REGISTRY_INVALID_RESULT_NAME'}
        if($entry.primitive_steps-isnot[array]-or@($entry.primitive_steps).Count-lt1-or@($entry.primitive_steps).Count-gt12){throw 'SKILL_REGISTRY_INVALID_PRIMITIVES'}
        foreach($primitive in @($entry.primitive_steps)){if(@('create_text','create_spreadsheet','ui_notepad_write')-cnotcontains[string]$primitive){throw 'SKILL_REGISTRY_UNAUTHORIZED_PRIMITIVE'}}
    }
}
function Registry(){
    if(-not(Test-Path -LiteralPath $reg)){
        # A missing registry is a first run only when no completed skills exist.
        # Existing receipts must never be discarded by inventing an empty history.
        if(@(Get-ChildItem -LiteralPath $sd -File -Filter '*.json'|Select-Object -First 1).Count){throw 'SKILL_REGISTRY_MISSING_WITH_PRIOR_EVIDENCE'}
        return [pscustomobject]@{schema=1;kind='kevin-composite-skill-registry';updated_at=(Get-Date).ToString('o');skills=@()}
    }
    $item=Get-Item -LiteralPath $reg -Force
    if($item.PSIsContainer-or($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0-or$item.Length-gt2097152){throw 'SKILL_REGISTRY_UNSAFE_OR_OVERSIZED_FILE'}
    $stream=$null;$reader=$null
    try{
        # Deny concurrent writes/deletion through this open handle and bound the
        # read itself, rather than relying only on an earlier file-size check.
        $stream=[IO.File]::Open($reg,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read)
        if($stream.Length-gt2097152){throw 'registry size bound'}
        $reader=New-Object IO.StreamReader($stream,(New-Object Text.UTF8Encoding($false,$true)),$true)
        $text=$reader.ReadToEnd();if(-not$text.TrimStart().StartsWith('{')){throw 'registry root must be an object'}
        $x=ConvertFrom-Json -InputObject $text -ErrorAction Stop
    }catch{throw 'SKILL_REGISTRY_UNREADABLE_PRESERVED'}finally{if($reader){$reader.Dispose()}elseif($stream){$stream.Dispose()}}
    Assert-RegistryValid $x
    return $x
}
function StartSkill($f){$x=Get-Content $f.FullName -Raw|ConvertFrom-Json;Skill $x;$mh=HO $x;$key=[string]$x.id+'@'+[string]$x.version;$rg=Registry;$old=@($rg.skills|?{[string]$_.key-eq$key});if($old.Count){if([string]$old[0].manifest_sha256-ne$mh){throw'proven manifest conflict'};$p=[pscustomobject]@{schema=1;kind='kevin-composite-skill-run';status='ALREADY_PROVEN';at=(Get-Date).ToString('o');manifest=$x;manifest_sha256=$mh;step_results=@()};W $f.FullName $p;return MoveR $f.FullName $sd};$now=(Get-Date).ToString('o');$s=[pscustomobject]@{schema=1;kind='kevin-composite-skill-run';status='RUNNING';started_at=$now;last_transition_at=$now;runner_heartbeat_at=$now;manifest=$x;manifest_sha256=$mh;step_index=0;current_order_id='';current_order_file='';current_order_state='';current_step_payload_sha256='';current_semantic_key='';step_started_at='';step_results=@();recovery_attempts=0;last_recovery_reason='';failure_evidence_sha256=''};$p=Join-Path $run ([string]$x.id+'--'+[string]$x.version+'.json');W $p $s;[void](Invoke-MissionLease 'Acquire' ([string]$x.id) ('reports/action-era/skills/running/'+[IO.Path]::GetFileName($p)));[void](Invoke-MissionLease 'Heartbeat' ([string]$x.id) ('reports/action-era/skills/running/'+[IO.Path]::GetFileName($p)));Remove-Item $f.FullName -Force;$p}
function Fail([string]$p,$s,[string]$why,$ev=$null){Note $s 'completed_at' '';Note $s 'failure_reason' '';$s.status='FAILED';$s.completed_at=(Get-Date).ToString('o');$s.failure_reason=$why;if($ev){$s.failure_evidence_sha256=HO $ev};W $p $s;if($s.manifest){[void](Invoke-MissionLease 'Release' ([string]$s.manifest.id) '' ('FAILED:'+$why))};[void](MoveR $p $sf);Write-Host('SKILL LAB FAILED '+$why)}
function DoneEvidence($o,$d){if(-not(Match $o $d)-or[string]$o.status-ne'DONE'){throw'DONE order fingerprint/status invalid'};$r=$o.result;if(-not$r-or[string]$r.status-ne'DONE'-or[string]::IsNullOrWhiteSpace([string]$r.completed_at)-or[string]::IsNullOrWhiteSpace([string]$r.output_name)-or[string]$r.sha256-notmatch'^[A-Fa-f0-9]{64}$'-or[int64]$r.bytes-lt0){throw'DONE result evidence invalid'};if($d.op-eq'ui_notepad_write'){if([string]$r.screenshot_sha256-notmatch'^[A-Fa-f0-9]{64}$'-or[string]::IsNullOrWhiteSpace([string]$r.screenshot_name)){throw'UI screenshot evidence invalid'}}}
function Consume([string]$p,$s,[int]$i,$rec,$d){DoneEvidence $rec.order $d;if(@($s.step_results|?{[string]$_.order_id-eq$d.id}).Count){throw'completion replay'};$r=$rec.order.result;$s.step_results=@($s.step_results)+@([pscustomobject]@{step_index=$i;operation=$d.op;order_id=$d.id;semantic_key=$d.key;payload_sha256=$d.ph;order_record_sha256=HO $rec.order;completed_at=[string]$r.completed_at;output_name=[string]$r.output_name;sha256=[string]$r.sha256;bytes=[int64]$r.bytes;screenshot_name=if($r.PSObject.Properties.Name-contains'screenshot_name'){[string]$r.screenshot_name}else{''};screenshot_sha256=if($r.PSObject.Properties.Name-contains'screenshot_sha256'){[string]$r.screenshot_sha256}else{''}});$s.step_index=$i+1;$s.current_order_id='';$s.current_order_file='';$s.current_order_state='';$s.current_step_payload_sha256='';$s.current_semantic_key='';$s.recovery_attempts=0;SaveT $p $s ('consumed '+$d.id)}
function Complete([string]$p,$s){$rg=Registry;$key=[string]$s.manifest.id+'@'+[string]$s.manifest.version;if(@($rg.skills|?{[string]$_.key-eq$key}).Count){throw'registry duplicate during completion'};Note $s 'completed_at' '';Note $s 'proof_sha256' '';$s.status='PROVEN';$s.completed_at=(Get-Date).ToString('o');$s.proof_sha256=HO $s;W $p $s;$rg.skills=@($rg.skills)+@([pscustomobject]@{key=$key;id=[string]$s.manifest.id;version=[string]$s.manifest.version;name=[string]$s.manifest.name;authority='GREEN';status='PROVEN';manifest_sha256=[string]$s.manifest_sha256;proof_sha256=[string]$s.proof_sha256;proven_at=$s.completed_at;primitive_steps=@($s.manifest.steps|%{[string]$_.operation});result_file=[IO.Path]::GetFileName($p)});$rg.updated_at=(Get-Date).ToString('o');Assert-RegistryValid $rg;W $reg $rg;[void](MoveR $p $sd);Write-Host('SKILL LAB PROVEN '+$key)}
function SelfTest{$m=[pscustomobject]@{schema=1;kind='kevin-composite-skill';id='selftest';version='1';authority='GREEN';name='Selftest';steps=@([pscustomobject]@{operation='create_text';payload=[pscustomobject]@{filename='selftest.txt';content='ok'}})};Skill $m;$s=[pscustomobject]@{manifest=$m};$d=D $s 0;$o=Order $s 0;if(-not(Match ([pscustomobject]$o) $d)){throw'reconcile selftest failed'};$o.payload.content='different';if(Match ([pscustomobject]$o) $d){throw'collision selftest failed'};$bad=$false;try{Step ([pscustomobject]@{operation='shell';payload=[pscustomobject]@{command='whoami'}})}catch{$bad=$true};if(-not$bad){throw'shell negative test failed'};Write-Host 'KEVIN SKILL LAB v1.0.3 SELFTEST PASS compatibility=v1.0.5-maintenance-v1.2';Write-Host 'KEVIN SKILL LAB v1.0.5 SELFTEST PASS primitives=3 crash_reconcile=1 registry_fail_closed=1 arbitrary_shell=false'}
if($SelfTest){SelfTest;if(-not(Test-Path -LiteralPath $LeaseBridge -PathType Leaf)){throw 'mission lease bridge missing'};$ls=& powershell -NoProfile -File $LeaseBridge -Action SelfTest 2>&1;if($LASTEXITCODE-ne0){throw ('mission lease wire selftest failed: '+(($ls|Out-String).Trim()))};Write-Host 'SKILL LAB MISSION-LEASE WIRE SELFTEST PASS';exit 0}
$m=New-Object Threading.Mutex($false,'Global\KevinSkillLab');$own=$false
try{$own=$m.WaitOne(0);if(-not$own){Write-Host 'SKILL LAB SKIP overlap';exit 0};[void](Registry);$f=Get-ChildItem $run -File -Filter '*.json' | Sort-Object LastWriteTime,Name | Select-Object -First 1;if(-not$f){$c=Get-ChildItem $rr -File -Filter '*.json' | Sort-Object LastWriteTime,Name | Select-Object -First 1;if(-not$c){Write-Host 'SKILL LAB NO_WORK';exit 0};try{$p=StartSkill $c}catch{$z=[pscustomobject]@{schema=1;kind='kevin-composite-skill-run';status='REJECTED';at=(Get-Date).ToString('o');failure_reason=$_.Exception.Message};W $c.FullName $z;[void](MoveR $c.FullName $sf);Write-Host('SKILL LAB REJECTED '+$_.Exception.Message);exit 0};if($p-like'*\done\*'){Write-Host 'SKILL LAB DUPLICATE already proven';exit 0};$f=Get-Item $p};$s=ReadJ $f.FullName;if(-not$s-or[string]$s.kind-ne'kevin-composite-skill-run'-or[string]$s.status-ne'RUNNING'){throw'running state invalid'};Skill $s.manifest;Init $s;$s.runner_heartbeat_at=(Get-Date).ToString('o');W $f.FullName $s;$steps=@($s.manifest.steps);$i=[int]$s.step_index;if($i-lt0-or$i-gt$steps.Count){throw'step_index invalid'};if($i-ge$steps.Count){Complete $f.FullName $s;exit 0};$d=D $s $i;$rec=Find $d.id
if([string]$s.current_order_id){if([string]$s.current_order_id-ne$d.id){Fail $f.FullName $s 'current_order_id mismatch';exit 0};if($rec){if(-not(Match $rec.order $d)){Fail $f.FullName $s 'work-order collision/replay mismatch' $rec.order;exit 0};if($rec.state-eq'FAILED'){Fail $f.FullName $s 'operator step failed' $rec.order;exit 0};if($rec.state-eq'DONE'){try{Consume $f.FullName $s $i $rec $d}catch{Fail $f.FullName $s $_.Exception.Message $rec.order;exit 0};if([int]$s.step_index-ge$steps.Count){Complete $f.FullName $s;exit 0};$i=[int]$s.step_index;$d=D $s $i;$rec=Find $d.id}else{$s.current_order_state=$rec.state;$s.runner_heartbeat_at=(Get-Date).ToString('o');W $f.FullName $s;Write-Host('SKILL LAB WAIT '+$d.id+' '+$rec.state);exit 0}}else{$age=Age ([string]$s.step_started_at);if($age-lt$staleMin){Write-Host('SKILL LAB WAIT transient missing order '+$d.id);exit 0};$s.recovery_attempts=[int]$s.recovery_attempts+1;if([int]$s.recovery_attempts-gt$maxRecover){Fail $f.FullName $s 'stale RUNNING recovery budget exhausted';exit 0};$s.current_order_id='';$s.current_order_file='';$s.current_order_state='';SaveT $f.FullName $s ('stale missing order reset attempt '+$s.recovery_attempts)}}
$i=[int]$s.step_index;$d=D $s $i;$rec=Find $d.id;if($rec){if(-not(Match $rec.order $d)){Fail $f.FullName $s 'work-order collision/replay mismatch' $rec.order;exit 0};if($rec.state-eq'FAILED'){Fail $f.FullName $s 'operator step failed (reconciled)' $rec.order;exit 0};if($rec.state-eq'DONE'){try{Consume $f.FullName $s $i $rec $d}catch{Fail $f.FullName $s $_.Exception.Message $rec.order;exit 0};if([int]$s.step_index-ge$steps.Count){Complete $f.FullName $s};exit 0};$s.current_order_id=$d.id;$s.current_order_file=[IO.Path]::GetFileName($rec.path);$s.current_order_state=$rec.state;$s.current_step_payload_sha256=$d.ph;$s.current_semantic_key=$d.key;SaveT $f.FullName $s ('adopted '+$rec.state+' '+$d.id);Write-Host('SKILL LAB RECOVERED adopted '+$d.id);exit 0}
$o=Order $s $i;$op=Join-Path $qr ($d.id+'.json');$s.current_order_id=$d.id;$s.current_order_file=[IO.Path]::GetFileName($op);$s.current_order_state='INTENT_PERSISTED';$s.current_step_payload_sha256=$d.ph;$s.current_semantic_key=$d.key;$s.step_started_at=(Get-Date).ToString('o');SaveT $f.FullName $s ('persisted enqueue intent '+$d.id);W $op $o;$s.current_order_state='READY';SaveT $f.FullName $s ('enqueued '+$d.id);Write-Host('SKILL LAB ENQUEUED '+$d.id)
}catch{Write-Host('SKILL LAB ERROR '+$_.Exception.Message);exit 1}finally{if($own){try{$m.ReleaseMutex()}catch{}};$m.Dispose()}

