param([ValidateSet('Poll','SelfTest')][string]$Mode='Poll')
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
$Utf8=New-Object Text.UTF8Encoding($false)
$Workspace=Join-Path $env:USERPROFILE '.openclaw\workspace'
$Control=Join-Path $Workspace 'ControlPlane'
$Reports=Join-Path $Workspace 'reports';if(-not(Test-Path $Reports)){$Reports=Join-Path $Workspace 'Reports'}
$LedgerPath=Join-Path $Control 'State\work-order-ledger-v1.json'
$LatestPath=Join-Path $Reports 'work-order-latest.json'
$CatalogPath=Join-Path $Control 'mission-catalog-v1.json'
$DispatcherPath=Join-Path $Control 'kevin-mission-dispatcher-v0.1.ps1'
$ActuatorPath=Join-Path $Control 'kevin-autonomy-actuator-v0.1.ps1'
$BridgePath=Join-Path $Control 'kevin-autonomy-bridge-v0.1.ps1'
$MaintenancePath=Join-Path $Workspace 'kevin-maintenance-runner.ps1'
$SupportPath=Join-Path $Reports 'support-latest.json'
$Repo='hessmodee/KEVIN-WORK';$OrderBranch='kevin-control-plane-v1';$OrderPath='control-plane/orders/CURRENT.json';$AckPath='reports/control-plane-latest.json'
New-Item -ItemType Directory -Force (Split-Path $LedgerPath -Parent)|Out-Null

function Write-JsonAtomic($o,[string]$p){$t=$p+'.tmp-'+$PID;[IO.File]::WriteAllText($t,($o|ConvertTo-Json -Depth 30),$Utf8);Move-Item $t $p -Force}
function Read-Json([string]$p){if(-not(Test-Path $p)){return $null};try{return Get-Content $p -Raw|ConvertFrom-Json}catch{return $null}}
function Prop($o,[string]$n){if($null-eq$o){return $null};$p=$o.PSObject.Properties[$n];if($p){return$p.Value};return $null}
function One([string]$s){if($null-eq$s){return''};$s=($s-replace'[\r\n]+',' ').Trim();if($s.Length-gt900){$s=$s.Substring(0,900)};return$s}
function Native([string]$exe,[string[]]$argv,[int]$timeout=600){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$exe;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.ArgumentList.Clear();foreach($a in $argv){[void]$psi.ArgumentList.Add([string]$a)};$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;if(-not$p.Start()){throw'process start failed'};$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not$p.WaitForExit($timeout*1000)){try{$p.Kill()}catch{};$p.Dispose();return[pscustomobject]@{ExitCode=124;Stdout='';Stderr='timeout'}};$r=[pscustomobject]@{ExitCode=[int]$p.ExitCode;Stdout=[string]$ot.Result;Stderr=[string]$et.Result};$p.Dispose();return$r}
function Gh([string[]]$a){$g=(Get-Command gh -ErrorAction Stop).Source;$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';$r=Native $g $a 90}finally{$ErrorActionPreference=$old};return$r}
function Remote([string]$path,[string]$branch){$r=Gh @('api',('repos/'+$Repo+'/contents/'+$path+'?ref='+[Uri]::EscapeDataString($branch)));if($r.ExitCode-ne0){if(($r.Stdout+$r.Stderr)-match'404|Not Found'){return$null};throw('GitHub GET failed '+(One($r.Stdout+$r.Stderr)))};$m=$r.Stdout|ConvertFrom-Json;$txt=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(([string]$m.content-replace'\s','')));return[pscustomobject]@{meta=$m;data=($txt|ConvertFrom-Json)}}
function Publish($o){$existing=Remote $AckPath 'main';$body=[ordered]@{message='kevin control plane telemetry';content=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(($o|ConvertTo-Json -Depth 20)));branch='main'};if($existing){$body.sha=[string]$existing.meta.sha};$tmp=Join-Path $env:TEMP ('kevin-ack-'+[guid]::NewGuid().ToString('N')+'.json');try{[IO.File]::WriteAllText($tmp,($body|ConvertTo-Json -Compress),$Utf8);$r=Gh @('api','--method','PUT',('repos/'+$Repo+'/contents/'+$AckPath),'--input',$tmp);if($r.ExitCode-ne0){throw'ack publish failed'}}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue}}
function Ledger{$x=Read-Json $LedgerPath;if($x){return$x};return[pscustomobject]@{schema=1;processed=@();updated_at=(Get-Date).ToString('o')}}
function SaveLedger($l){$l.processed=@($l.processed|Select-Object -Last 100);$l.updated_at=(Get-Date).ToString('o');Write-JsonAtomic $l $LedgerPath}

function Validate($o){$allowed=@('schema','kind','id','idempotency_key','created_at','expires_at','authority_class','verb','target','reason');foreach($p in $o.PSObject.Properties.Name){if($allowed-notcontains[string]$p){throw('Unknown work-order property: '+$p)}};foreach($n in @('schema','kind','id','idempotency_key','created_at','expires_at','authority_class','verb','target')){if($null-eq(Prop $o $n)){throw('Missing required property: '+$n)}};if([int]$o.schema-ne1-or[string]$o.kind-ne'kevin-work-order'-or[string]$o.authority_class-ne'GREEN'){throw'Work-order contract mismatch'};$created=[DateTimeOffset]::Parse([string]$o.created_at);$expires=[DateTimeOffset]::Parse([string]$o.expires_at);$now=[DateTimeOffset]::Now;if($expires-le$now){throw'Work order is expired.'};if($created-gt$now.AddMinutes(10)-or($expires-$created).TotalHours-gt24){throw'Work-order time window invalid'};$verbs=@('dispatch_mission','run_reconcile','run_benchmark','run_support_bridge','refresh_autonomy_telemetry','run_typed_maintenance');if($verbs-notcontains[string]$o.verb){throw('Verb is not GREEN allowlisted: '+[string]$o.verb)};switch([string]$o.verb){'dispatch_mission'{$c=Read-Json $CatalogPath;if(-not$c-or@($c.missions|?{[string]$_.id-eq[string]$o.target}).Count-ne1){throw'mission target not catalogued'}}'run_reconcile'{if([string]$o.target-ne'autonomy'){throw'target mismatch'}}'run_benchmark'{if([string]$o.target-ne'kevin-benchmark-v1'){throw'target mismatch'}}'run_support_bridge'{if([string]$o.target-ne'kevin-support-bridge-v1'){throw'target mismatch'}}'refresh_autonomy_telemetry'{if([string]$o.target-ne'autonomy-telemetry'){throw'target mismatch'}}'run_typed_maintenance'{if([string]$o.target-ne'kevin-maintenance-v1'){throw'target mismatch'}}}}
function Ocl([string[]]$a){$node=(Get-Command node.exe -ErrorAction Stop).Source;$cli=Join-Path $env:APPDATA 'npm\node_modules\openclaw\dist\index.js';$r=Native $node (@($cli)+$a) 540;if($r.ExitCode-ne0){throw('OpenClaw failed '+(One($r.Stdout+$r.Stderr)))};if(-not$r.Stdout.Trim()){return$null};return$r.Stdout|ConvertFrom-Json}
function JobId([string]$key){$s=Read-Json $SupportPath;$j=@($s.cron.jobs|?{[string]$_.declaration_key-eq$key})|Select-Object -First 1;if(-not$j){throw('job not found '+$key)};return[string]$j.id}
function RunJob([string]$key,[int]$mins){$id=JobId $key;$null=Ocl @('cron','run',$id,'--wait','--wait-timeout',($mins.ToString()+'m'),'--poll-interval','2s');return('verified job='+$id)}
function Ps([string]$file,[string[]]$a=@(),[int]$seconds=600){$r=Native 'powershell.exe' (@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$file)+$a) $seconds;if($r.ExitCode-ne0){throw('fixed local action failed '+(One($r.Stdout+$r.Stderr)))};return One $r.Stdout}
function Execute($o){switch([string]$o.verb){'dispatch_mission'{return Ps $DispatcherPath @('-Mode','Dispatch','-RequestedMission',[string]$o.target) 560}'run_reconcile'{return Ps $ActuatorPath @('-Mode','Reconcile') 600}'run_benchmark'{return RunJob 'kevin-benchmark-v1' 9}'run_support_bridge'{return RunJob 'kevin-support-bridge-v1' 5}'refresh_autonomy_telemetry'{$env:KEVIN_GH_AUTH_MODE='stored';return Ps $BridgePath @() 180}'run_typed_maintenance'{return Ps $MaintenancePath @('-CheckOnly') 600}};throw'No executor'}

function SelfTest{$good=[pscustomobject]@{schema=1;kind='kevin-work-order';id='selftest-maint-01';idempotency_key='selftest-maintenance-once';created_at=(Get-Date).AddMinutes(-1).ToString('o');expires_at=(Get-Date).AddMinutes(10).ToString('o');authority_class='GREEN';verb='run_typed_maintenance';target='kevin-maintenance-v1';reason='selftest'};Validate $good;$bad=$good|ConvertTo-Json|ConvertFrom-Json;$bad|Add-Member command 'whoami';$blocked=$false;try{Validate $bad}catch{$blocked=$true};if(-not$blocked){throw'command injection accepted'};$bad=$good|ConvertTo-Json|ConvertFrom-Json;$bad.target='arbitrary';$blocked=$false;try{Validate $bad}catch{$blocked=$true};if(-not$blocked){throw'arbitrary target accepted'};Write-Host 'KEVIN WORK ORDER INTAKE v1.2 SELFTEST PASS verbs=6 maintenance_target=fixed arbitrary_shell=false caller_argv=false'}
if($Mode-eq'SelfTest'){SelfTest;exit 0}

$ack=[ordered]@{schema=1;kind='kevin-control-plane-ack';generated_at=(Get-Date).ToString('o');request=$null;status='NO_ORDER';detail='';safety=[ordered]@{green_only=$true;arbitrary_shell=$false;authority_expansion=$false}}
try{$remote=Remote $OrderPath $OrderBranch;if(-not$remote){$ack.detail='No work order';Publish $ack;exit 0};$o=$remote.data;$ack.request=[ordered]@{id=[string]$o.id;verb=[string]$o.verb;target=[string]$o.target};Validate $o;$l=Ledger;if(@($l.processed|?{[string]$_.idempotency_key-eq[string]$o.idempotency_key}).Count){$ack.status='DUPLICATE_IGNORED';$ack.detail='Idempotency key already processed';Publish $ack;exit 0};$result=Execute $o;$l.processed=@($l.processed)+@([pscustomobject]@{id=[string]$o.id;idempotency_key=[string]$o.idempotency_key;at=(Get-Date).ToString('o');status='SUCCESS'});SaveLedger $l;$ack.status='SUCCESS';$ack.detail=One $result;Publish $ack;exit 0}catch{$ack.status='FAILED';$ack.detail=One $_.Exception.Message;try{Publish $ack}catch{};exit 1}
