from pathlib import Path

src=Path('control-plane/maintenance/kevin-maintenance-runner-v1.3.29.ps1')
dst=Path('control-plane/maintenance/kevin-maintenance-runner-v1.3.30.ps1')
text=src.read_bytes().decode('utf-8')
nl='\r\n' if '\r\n' in text else '\n'

if text.count("version='1.3.29'") != 1:
    raise SystemExit('Maintenance v1.3.29 version marker mismatch')
text=text.replace("version='1.3.29'","version='1.3.30'",1)

needle="    if([int]$r.exit_code -eq 0){return 'OK'}"
if text.count(needle)!=1:
    raise SystemExit('gateway classifier anchor mismatch')
extra=(
"    if($t -match '(?i)ERR_MODULE_NOT_FOUND|Cannot find module|Cannot find package'){return 'MODULE_LOAD_FAILURE'}"+nl+
"    if($t -match '(?i)invalid config|configuration.{0,40}invalid|config.{0,40}error|validation failed|unknown config|unrecognized config|schema.{0,40}(invalid|error)'){return 'CONFIG_INVALID'}"+nl+
"    if($t -match '(?i)SyntaxError|Unexpected token|parse error'){return 'RUNTIME_PARSE_FAILURE'}"+nl+
"    if($t -match '(?i)unsupported.{0,30}node|requires Node|Node.{0,30}version'){return 'NODE_VERSION_INCOMPATIBLE'}"+nl+
"    if($t -match '(?i)ENOENT|file not found|path not found'){return 'FILE_NOT_FOUND'}"+nl
)
text=text.replace(needle,extra+needle,1)

start="function Diagnose-GatewayRpc {"+nl+"    $basic=Invoke-OpenClawFixedConfig @('gateway','status','--json')"
if text.count(start)!=1:
    raise SystemExit('Diagnose-GatewayRpc start anchor mismatch')
replacement=(
"function Diagnose-GatewayRpc {"+nl+
"    $runtime=Get-FixedOpenClawRuntime"+nl+
"    $nodeVersion=Invoke-FixedNativeBounded $runtime.node @('--version') 30"+nl+
"    $cliVersion=Invoke-FixedNativeBounded $runtime.node @($runtime.cli,'--version') 30"+nl+
"    $cliHelp=Invoke-FixedNativeBounded $runtime.node @($runtime.cli,'--help') 30"+nl+
"    $defaultConfig=Join-Path $env:USERPROFILE '.openclaw\\openclaw.json'"+nl+
"    $configExists=Test-Path -LiteralPath $defaultConfig -PathType Leaf"+nl+
"    $configSha=if($configExists){Get-Sha $defaultConfig}else{''}"+nl+
"    $configSize=if($configExists){[int64](Get-Item -LiteralPath $defaultConfig).Length}else{0}"+nl+
"    $strictJsonValid=$false"+nl+
"    if($configExists){try{$null=Get-Content -LiteralPath $defaultConfig -Raw|ConvertFrom-Json;$strictJsonValid=$true}catch{}}"+nl+
"    $basic=Invoke-OpenClawFixedConfig @('gateway','status','--json')"
)
text=text.replace(start,replacement,1)

report_anchor="        openclaw_version=$pkgVersion"+nl+"        probes=[ordered]@{"
if text.count(report_anchor)!=1:
    raise SystemExit('public report anchor mismatch')
report_repl=(
"        openclaw_version=$pkgVersion"+nl+
"        bootstrap=[ordered]@{"+nl+
"            node_version=[ordered]@{exit_code=[int]$nodeVersion.exit_code;class=(Get-GatewayProbeClass $nodeVersion);output_sha256=(Get-TextSha256 ([string]$nodeVersion.output))}"+nl+
"            cli_version=[ordered]@{exit_code=[int]$cliVersion.exit_code;class=(Get-GatewayProbeClass $cliVersion);output_sha256=(Get-TextSha256 ([string]$cliVersion.output))}"+nl+
"            cli_help=[ordered]@{exit_code=[int]$cliHelp.exit_code;class=(Get-GatewayProbeClass $cliHelp);output_sha256=(Get-TextSha256 ([string]$cliHelp.output))}"+nl+
"        }"+nl+
"        config_file=[ordered]@{exists=[bool]$configExists;sha256=$configSha;size_bytes=$configSize;strict_json_valid=[bool]$strictJsonValid}"+nl+
"        probes=[ordered]@{"
)
text=text.replace(report_anchor,report_repl,1)

old_final="Write-Host 'KEVIN MAINTENANCE v1.3.29 SELFTEST PASS autonomy_controller_contract=legacy_v183 supervisor_v184=true selector_v11=true openclaw_native_node=true shell_shim_bypassed=true baseline_anchor=atomic rollback=true arbitrary_shell=false authority_expansion=false'"
if text.count(old_final)!=1:
    raise SystemExit('v1.3.29 selftest marker mismatch')
new_final=old_final+nl+"    Write-Host 'KEVIN MAINTENANCE v1.3.30 SELFTEST PASS openclaw_bootstrap_diagnosis=fixed node_probe=fixed cli_version_probe=fixed config_metadata_only=true gateway_classifier=expanded arbitrary_shell=false authority_expansion=false'"
text=text.replace(old_final,new_final,1)

for required in ('MODULE_LOAD_FAILURE','CONFIG_INVALID','node_version','cli_version','strict_json_valid','config_metadata_only=true'):
    if required not in text: raise SystemExit('missing '+required)

dst.write_bytes(text.encode('utf-8'))
print(f'MAINT_V1330_GENERATED bytes={dst.stat().st_size}')
