from pathlib import Path

src = Path('control-plane/maintenance/kevin-maintenance-runner-v1.3.28.ps1')
dst = Path('control-plane/maintenance/kevin-maintenance-runner-v1.3.29.ps1')
text = src.read_bytes().decode('utf-8')
nl = '\r\n' if '\r\n' in text else '\n'

old_sha = "29122F147233DC672DC6AFF4D5AD4262D4512B39D67CC42628DB6C5C78D811FB"
new_sha = "BBE4F4947E5D5BEFCBB82890F63EE4A68C0F39375A627F311036EDBB78665940"
old_src = "control-plane/autonomy/kevin-supervisor-v1.8.3.ps1"
new_src = "control-plane/autonomy/kevin-supervisor-v1.8.4.ps1"

if text.count(old_sha) != 1:
    raise SystemExit(f'unexpected old Supervisor hash count: {text.count(old_sha)}')
text = text.replace(old_sha, new_sha, 1)
if text.count(old_src) != 1:
    raise SystemExit(f'unexpected old Supervisor source count: {text.count(old_src)}')
text = text.replace(old_src, new_src, 1)

if text.count("version='1.3.28'") != 1:
    raise SystemExit('unexpected Maintenance version marker count')
text = text.replace("version='1.3.28'", "version='1.3.29'", 1)

start = text.find('function Install-AutonomyControllerV183([object]$m) {')
end = text.find('function Process-Typed([object]$m) {', start)
if start < 0 or end <= start:
    raise SystemExit('unable to isolate autonomy installer')
block = text[start:end]
if 'v1.8.3' not in block:
    raise SystemExit('installer block lacks v1.8.3 markers')
block = block.replace('v1.8.3', 'v1.8.4')
block = block.replace("fixed_main_agent=$true;anti_spin=$true;rollback_available=$true", "fixed_main_agent=$true;anti_spin=$true;openclaw_native_node=$true;shell_shim_bypassed=$true;rollback_available=$true")
text = text[:start] + block + text[end:]

old_final = "Write-Host 'KEVIN MAINTENANCE v1.3.28 SELFTEST PASS openclaw_native_node=true shell_shim_bypassed=true native_timeout=180s gateway_direct_rpc=true fixed_main_canary=true arbitrary_shell=false authority_expansion=false'"
if text.count(old_final) != 1:
    raise SystemExit('v1.3.28 final selftest marker missing')
new_final = old_final + nl + "    Write-Host 'KEVIN MAINTENANCE v1.3.29 SELFTEST PASS autonomy_controller_contract=legacy_v183 supervisor_v184=true selector_v11=true openclaw_native_node=true shell_shim_bypassed=true baseline_anchor=atomic rollback=true arbitrary_shell=false authority_expansion=false'"
text = text.replace(old_final, new_final, 1)

# The operation name is retained solely as a backwards-compatible typed contract ID.
anchor = "$SupervisorV183Source = 'control-plane/autonomy/kevin-supervisor-v1.8.4.ps1'"
if text.count(anchor) != 1:
    raise SystemExit('qualified Supervisor source anchor missing')
text = text.replace(anchor, anchor + nl + "# Legacy v183 symbol/operation name is retained as the typed contract identifier; its qualified target is Supervisor v1.8.4.", 1)

if old_sha in text or old_src in text:
    raise SystemExit('old Supervisor identity remains')
if new_sha not in text or new_src not in text:
    raise SystemExit('new Supervisor identity missing')
if text.count("install_autonomy_controller_v183") < 5:
    raise SystemExit('legacy typed contract unexpectedly changed')

dst.write_bytes(text.encode('utf-8'))
print(f'MAINT_V1329_GENERATED bytes={dst.stat().st_size}')
